# -*- coding: utf-8 -*-
# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2026 Calibre-Web contributors
# Copyright (C) 2024-2026 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# See CONTRIBUTORS for full list of authors.

# SPDX-License-Identifier: GPL-3.0-or-later
"""Extraction anchors for SPA-only translatable strings.

The React SPA's English source strings ARE the gettext msgids (see
cps/api/i18n.py — the per-locale JSON catalog is derived from the same .po files
the classic UI uses). But pybabel only scans Python + Jinja (babel.cfg), so a
string that appears ONLY in the .tsx SPA is dropped from messages.pot on the
next re-extract — and msgmerge then marks its translations obsolete, so the SPA
silently falls back to English (this is exactly how #577's "Read now" → "Nu
lezen" was lost after the auto-translation job ran).

Referencing those SPA-only msgids here, with the gettext marker, keeps them in
the catalog across re-extracts. This module is never imported and does nothing at
runtime — babel reads the *source*, not the call result; ``_`` is a local no-op,
not flask_babel's request-scoped gettext (which can't run at import time).

Add a SPA-only msgid here the moment you introduce it in the frontend.
"""


def _(message):  # noqa: E743 - intentional gettext extraction marker, not the builtin
    return message


_("{succeeded} added to the shelf; {failed} failed.")
_("{succeeded} book(s) deleted; {failed} failed.")
_("{succeeded} book(s) permanently deleted from the global library for every user; {failed} failed.")
_("{succeeded} book(s) removed from your library; {failed} failed.")
_("{succeeded} updated; {failed} failed.")
_("Metadata applied to {succeeded}; {failed} failed.")
_("A book must keep at least one format.")
_("{succeeded} book(s) permanently deleted; {warnings} deleted with cleanup warnings; {failed} failed.")
_("Cleanup warning for book {id}: {message}")
_("Book {id}: {message}")
_("Failed: {failures}. The failed books remain selected; choose the action again to retry.")
_("Could not delete this format.")
_("Format deleted.")


# #577 — the new-UI "open the reader" button. A distinct msgid from the "Read"
# read-status label (which is a past participle in many languages, e.g. nl
# "Gelezen") so the verb and the status can be translated separately.
_("Read now")
_("Open details for {title}")
_("Read {title}")

# Built-in magic-shelf names are canonical English database identity but are
# translated as request-local display text by the SPA API. They do not appear
# as literals in .tsx, so keep them in the SPA fuzzy-quality population here.
_("Recently Added")
_("Highly Rated")
_("Currently Reading")
_("Yet to Read")
_("Recent Publications")

# The SPA admin security endpoint sends these labels as data and Admin.tsx
# translates them at render time. Keep the complete backend-owned enums in the
# catalog: the TSX extractor cannot discover Python registry values.
_("Standard (username / password)")
_("LDAP")
_("OAuth / OpenID Connect")
_("Anonymous")
_("Unauthenticated")
_("Simple (service account)")
_("None")
_("TLS")
_("SSL")

# #573 — the new-UI series view's series-order sort options (Catalog.tsx). Only
# shown when viewing a single series, so the reader can order by position.
_("Series order")
_("Series order (reverse)")

# #572 — inline tag add/remove on the book detail page (quick-edit, no full
# editor). SPA-only strings, anchored so the auto-translation job keeps them.
_("Add tag")
_("New tag")
_("Remove tag")
# NB: the SPA's interpolate() uses {brace} placeholders, not gettext %(name)s —
# a %()s msgid renders its placeholder literally (was a latent bug here + in
# BulkBar). Keep SPA msgids on the {brace} form.
_("Remove tag {name}")
_("Rename tag {name}")
_("Tag name")
_("Tag name cannot be empty")
_("Save tag name")
_("Select format")
_("Could not rename tag")
_("Tag renamed to {name}")
_("You must be signed in")
_("You are not allowed to edit metadata")
_("Tag not found")
_("A tag with that name already exists")
_("Tag name must be text")
_("Tag name cannot contain commas")
_("Enter a valid tag name")
_("Could not load this page")
_("Page not found")

# #1939 — My Library: named modes, global discovery, membership actions,
# onboarding, empty/denied states and administrator controls. These strings
# live in the React client; keep every one anchored so extraction cannot make a
# completed locale silently fall back to English.
_("Add")
_("Add to my library")
_("Add {title} to my library")
_("Added to your library")
_("Added to your library and to {shelf}")
_("Adding this book to a shelf also adds it to your library.")
_("Adding…")
_("Add book to this library")
_("Book ID")
_("Added book {book} to {name}.")
_("Browse global library")
_("Browse the global library")
_("Could not add the book.")
_("Could not add this book to the shelf.")
_("Could not add the book. Please try again.")
_("Could not remove the book. Please try again.")
_("Permanently delete {n} selected book(s) from the global library for every user? The books and all their files will be erased from the server. This cannot be undone.")
_("Remove {n} selected book(s) from your library? They leave your library and your OPDS feed. They are also removed from any regular shelves you added them to. Nothing is deleted from the global library. Highlights, notes, bookmarks, and reading progress are kept. If you use Kobo's built-in sync, the books also leave each Kobo device on your account at its next sync; other e-readers keep downloaded copies.")
_("The last book cannot be removed unless you can browse the global library.")
_("The server rejected a batch as too large (maximum {max} books).")
_("The server rejected a batch as too large.")
_("Delete \"{title}\" from the global library? The book and all its files are permanently erased for every member. This cannot be undone.")
_("Delete from the global library")
_("Every book here is already in your library.")
_("Everything on the server, including every new book added to it.")
_("Enter a valid book ID.")
_("Give {name} their own selection? It starts as a copy of everything they can see now — nothing changes for them yet.")
_("Global Library")
_("In your library")
_("It also leaves these shelves: {shelves}.")
_("Keep your own selection again? Your library goes back to the books you had chosen — nothing was lost while you saw everything. At its next update, your e-reader returns to your selection.")
_("Library contents")
_("Library scope")
_("My Library")
_("My selection")
_("New: your own library")
_("Not in your library")
_("Nothing is deleted: the book stays in the global library, and your highlights, notes and reading progress are kept.")
_("Nothing is missing — the whole library is still on the server. What you see here is your own selection. Add books from the global library; they appear here and on your e-reader.")
_("Only an administrator can add it back.")
_("Only the books chosen for this account.")
_("Only the books you choose. Add them from the global library; remove them any time.")
_("Own selection")
_("Recently added")
_("Remove \"{title}\" from your library?")
_("Remove from my library")
_("Remove {title} from my library")
_("Removed from your library")
_("Removing…")
_("Search the global library for \"{query}\" instead")
_("Set up My Library for all users")
_("Set up My Library for every non-anonymous account? Each account starts with every book it can currently see—not only books it has shelved, read, or downloaded. Users can curate from there by removing books. Accounts already set up are never reseeded.")
_("Set up My Library for every non-anonymous user? Each account switches to its own selection after it is filled with everything that account can currently see. Anonymous accounts such as Guest are left unchanged; use their per-user controls to set up a curated public library. Accounts set up before are never reseeded.")
_("Set up {accounts} accounts with {books} books. {errors} errors.")
_("Left anonymous accounts unchanged: {accounts}. Use their per-user controls to set up a curated public library.")
_("Show the whole library again? Your selection is kept exactly as you left it — switch back any time and it is still there. At its next update, your e-reader syncs the whole library.")
_("Show {name} the whole library again? Their selection is kept but no longer used, and their e-reader syncs the whole library at the next update.")
_("Start your own selection? It begins as everything you can see now, so nothing changes until you remove books yourself. Your e-reader keeps the same books at its next update.")
_("Switch {name} back to their own selection? Their chosen books are restored.")
_("Switching a user to their own selection first fills it with everything they can see now, so nothing changes for them until they remove books themselves. Switching back keeps the selection intact but unused.")
_("The library is shared and holds every book once — what you keep is your own selection. Nothing you had is gone. Every book, new arrivals included, is under Global Library in the menu.")
_("The library is shared and holds every book once — what you keep is your own selection. Nothing you had is gone. Your administrator manages what enters your selection.")
_("It leaves your library and your OPDS feed.")
_("If you use Kobo's built-in sync, it also leaves your Kobo at its next sync. Other e-readers keep downloaded copies, and KOReader progress sync keeps working.")
_("The whole archive. Add books to your library from here.")
_("The whole library")
_("Without the global-browse role, only an administrator can add books to this user's library.")
_("You can add it back any time from the global library.")
_("You don't have access to the global library. Ask an administrator to grant it.")
_("Your administrator chooses which books are in your library. Ask them to add books, or to let you browse the global library.")
_("Your library contents are managed by an administrator.")
_("Your library is empty")
_("{name} now keeps their own selection.")
_("{name} sees the whole library again.")

# Book detail completeness pass — star rating (parity with the classic detail
# page) and the "More by this author" browse strip that fills the page for
# sparse books. SPA-only strings (BookDetail.tsx / StarRating.tsx /
# MoreByAuthor.tsx), anchored so the auto-translation job keeps them.
_("Clear rating")
_("Not rated")
_("Yes")
_("No")
_("Email Message Body")
_("This Email has been sent via Calibre-Web NextGen.")
_("Rated {rating} out of 5")
_("More by {name}")
_("Send to device")
_("Device")
_("Collects on the device's next sync.")
_("Choose a device")
_("Queueing…")
_("Book queued for this device")
_("This book is already queued for this device")
_("This book is already on that device")
_("Could not queue this book for the device.")

# Bulk-selection toolbar (BulkBar.tsx) — previously unanchored AND written with
# %(n)s, so they were dropped on re-extract and rendered the placeholder
# literally in a visible confirm dialog + button. Anchored on the {brace} form.
_("Merge {n} books into the first selected? The others are removed after their formats are copied over.")
_("Apply to {n} books")

# #736 cross-screen theme sweep — accessible names for the smart-shelf rule
# selects (previously unlabeled -> axe select-name critical).
_("Match condition")
_("Rule field")
_("Rule operator")
_("Could not load smart-shelf rules.")
_("Has Cover")
_("Series Index")
_("Read Status")
_("Has Hardcover ID")
_("In the past N days")
_("Not in the past N days")
_("is before / less than")
_("is on or before / at most")
_("is after / greater than")
_("is on or after / at least")
_("is between")
_("is not between")
_("does not begin with")
_("does not end with")
_("is empty")
_("is not empty")

# #736 — per-user theme picker
_("Appearance")
_("Theme")
_("System")
_("Light")
_("Dark")
_("Sepia")
_("High contrast")
_("Midnight (AMOLED)")
_("Match your device’s light or dark setting")
_("Theme saved.")
_("Could not save theme.")
_("Default theme for new accounts")
_("Applies to accounts created from now on. Everyone picks their own under Account → Theme.")


# ============================================================================
# Accessibility remediation (WCAG 2.2 AA sweep) — SPA-only strings introduced by
# the a11y pass: skip link, live-region announcements, ARIA labels for icon-only
# controls, reader/annotation color names, form/error messages. Anchored so the
# auto-translation job keeps them (babel does not scan .tsx).
# ============================================================================
_('Add a format')
_('Add rule')
_('Add to shelf')
_('Add your own')
_('App password label')
_('App passwords')
_('Author')
_('Authors (separate with &)')
_('Back to book')
_('Back to sign in')
_('Blue')
_('Book content')
_('Browse')
_('Change password')
_('Close')
_('Close menu')
_('Contents')
_('Convert failed.')
_('Convert to')
_('Convert to format')
_('Copy')
_('Could not change password.')
_('Could not create.')
_('Could not fetch cover.')
_('Could not load metadata.')
_('Could not load the book file ({status})')
_('Could not load your account.')
_('Could not save.')
_('Cover')
_('Cover image URL')
_('Cover update failed.')
_('Cover updated.')
_('Create smart shelf')
_('Create your account')
_('Dark')
_('Dark theme')
_('Delete')
# #803 — the new-UI book-detail whole-book delete control + confirm + states.
_('Delete book')
_('Delete "{title}"? This permanently removes the book and all its files from your library. This cannot be undone.')
_('Deleting…')
_('Could not delete this book.')
_('Delete the {fmt} file? The book stays; only this format is removed.')
_('Delete {fmt}')
_('Delete {n} book(s)? This cannot be undone.')
_('Description contains')
_('Deselect {title}')
_('Edit metadata')
_('Edit {title}')
# #928 — the saved default library view (#498) renders as a filtered library,
# so the notice strip that explains the subset lives on Catalog.tsx.
_('Showing your default library view.')
_('Show all books')
_('Edit default view')
_('Failed to load books.')
_('Failed to open the book.')
_('Generate')
_('Green')
_('Help')
_('Highlight color')
_('Import from Kobo')
_('Interface language')
_('Invalid username or password.')
# #701 — UI font preset picker (Account page + lib/fonts.ts)
_('UI body font')
_('UI display font')
_('Default (Optima / Sans-Serif)')
_('Default (Bookish Serif)')
_('System Sans-Serif')
_('Bookish Serif')
_('Monospace')
_('Label (e.g. KOReader on phone)')
_('Languages (comma separated)')
_('Light')
_('Light theme')
_('Login failed.')
_('Mark read')
_('Mark unread')
_('Merge')
_('Metadata applied to {n} book(s).')
_('New password for “{label}” — copy it now, it won’t be shown again:')
_('New passwords do not match.')
_('No books here.')
_('No results for "{q}".')
_('No suggestions')
_('No {filter} books here.')
_('Password changed.')
_('Paste URL')
_('Private shelf')
_('Profile')
_('Profile saved.')
_('Public shelf')
_('Publisher')
_('Publishers (comma separated)')
_('Read')
_('Reading')
_('Reading progress')
_('Red')
_('Registration failed.')
_('Remove {name}')
_('Request failed.')
_('Reset')
_('Reset your password')
_('Revoke {label}')
_('Save changes')
_('Save failed.')
_('Save profile')
_('Saved.')
_('Saving…')
_('Search')
_('Search failed.')
_('Search for metadata')
_('Metadata providers')
_('Loading providers…')
_('Could not load providers.')
_('Could not update provider.')
_('{provider}: {state}')
_('On')
_('Off')
_('Search results')
_('Search the library')
_('Select {title}')
_('Sepia')
_('Sepia theme')
_('Series')
_('Series position {n}')
# #657 — series name + position shown under the cover on book cards (BookCard.tsx)
_('{series} #{n}')
_('Sign in')
_('Sign in failed. Please try again.')
_('Skip to content')
_('Some fields could not be saved.')
_('Table of contents')
_('Tags (comma separated)')
_('Title')
_('Unread')
_('Update password')
_('Upload')
_('Choose books to upload')
_('Upload failed.')
_('Upload image')
_('Uploading…')
_('Yellow')
_('e.g. MOBI')
_('{format} reader')
_('{name} API key')
_('{n} book(s) added to the shelf.')
_('{n} book(s) deleted.')
_('{n} book(s) permanently deleted from the global library for every user.')
_('{n} book(s) removed from your library.')
_('{n} marked as read.')
_('{n} marked as unread.')
_('{n} selected')
_('{pct}% read')
# "What's new" in-app feature log (SPA /whats-new + the Help menu entry). The
# page CHROME is localized; the per-release entry copy in data/whatsNew.ts is
# English by design (documented on the page). Category names double as the chip
# labels AND the WhatsNewCategory union values — keep them in sync with
# frontend/src/data/whatsNew.ts if that union ever changes.
_("What's new")
_("Help — new updates available")
_("The latest features and fixes in Calibre-Web NextGen — newest first.")
_("{n} update")
_("{n} updates")
_("No release notes yet — check back after the next update.")
_("The interface is translated into your language; these update notes are written in English.")
# Category chips (must match the WhatsNewCategory union)
_("Reading")
_("Grid view")
_("Library")
_("List view")
_("Sync")
_("Account")
_("Admin")
_("Under the hood")
# "Try it" deep-link button labels (data-authored, but stable enough to anchor
# so a reader's locale can translate the call-to-action).
_("Open your library")
_("Browse tags")
_("Open the table view")
_("Review duplicates")
_("Open your shelves")
_("Manage sync & app passwords")
_("Check your e-reader address")
_("Create an app password")
_("Browse series")
_("Browse authors")
_("Browse languages")
_("Open Table view")
_("Open Admin")
_("Open account settings")
_("Browse Discover")
_("Explore your library")
_("Go to Upload")
_("Open Tasks")
_("Open search")
# Metadata edit — Hardcover editions drill-down (EditBook.tsx)
_("Editions")
_("Back to New UI")
_("Back to results")
_("No editions found for this book.")
# Metadata edit — full-record "View all details" overlay (EditBook.tsx)
_("View all details")
_("Result details")
_("Published")
_("Format")
_("Source")
# #585 — in-sidebar "Customize" capsule + inline edit mode (Sidebar.tsx +
# SidebarEditList.tsx): reorder and hide/restore sidebar sections from the new UI.
_("Customize")
_("Customize sidebar")
_("Customize navigation")
_("Done")
_("Reset to default")
_("Always shown")
_("Editing sidebar. Reorder or hide sections, then tap Done.")
_("Editing cancelled.")
_("Drag to reorder. Tap ✕ to hide a section. Arrow keys move the focused handle.")
_("Sidebar saved.")
_("Sidebar reset to default.")
_("{label} moved to position {pos} of {total}")
_("Reorder {label} (position {pos} of {total}). Use arrow keys to move.")
_("Delete {label}")
_("Restore {label}")
_("{label} hidden")
_("{label} restored")
_("Could not save sidebar. Please try again.")

# #780 / #665 — manual library scan button in the catalog toolbar (Catalog.tsx).
# The SPA had no equivalent of the classic header's "Refresh Library" action.
# Deliberately a distinct (lowercase-l) msgid from the classic "Refresh Library"
# so the button can read in sentence case; anchored so the auto-translation job
# keeps it across re-extracts.
_("Refresh library")


# ---- Restored anchors (regression guard) --------------------------------
# `extract_spa_strings.py --write` regenerates the AUTOGEN block below from
# what its parser can see in the frontend. Strings it cannot see statically
# — dynamic keys, values built at runtime — were previously anchored inside
# that block and were dropped when it was regenerated on 2026-08-09, which
# obsoleted their msgids and lost the existing fr/ru/de translations (the
# #615 symptom: an untranslated SPA msgid renders English rather than
# failing). They live ABOVE the marker so regeneration cannot drop them again.
#
# 30 of the 31 are restored. "Border fill style" is deliberately NOT among them:
# nothing renders it. The classic cover picker's dropdown is labelled
# _('Fill style') (cover_picker.html:114) and the SPA's is t('Fill style')
# (CoverPicker.tsx:205) -- both of which are anchored and translated. The
# phrase survives only in changelog prose and a test comment, and no locale has
# ever carried a translation for it. Re-anchoring it puts a msgid nobody can
# see back into the SPA-chrome catalog, which is what the #615 completeness
# gate then requires fr and nl to translate. Do not add it back.
_("<")
_("=")
_(">")
_("A one-time full duplicate scan is needed. Run it from CWA settings, then return here.")
_("Date Added")
_("Delete \u201c{name}\u201d? It is removed from {count} book, which is kept.")
_("Delete \u201c{name}\u201d? It is removed from {count} books, which are kept.")
_("Delete")
_("Dismiss Ko-fi support message")
_("Dismiss help announcement")
_("Kobo book compatibility repaired")
_("Library notice")
_("Show affected books")
_("Untitled book")
_("{count} notices dismissed permanently.")
_("There is new information about your library.")
_("Dismiss all {count} notices permanently")
_("Dismiss all")
_("There is new information about this book.")
_("Notice dismissed permanently.")
_("Dismiss permanently")
_("Could not dismiss the notices. Please try again.")
_("Could not dismiss the notice. Please try again.")
_("Merge")
_("Open Ko-fi →")
_("Publication Date")
_("Saving…")
_("Support us on Ko-fi!")
_("These open the full configuration pages. Changes there apply to the whole server.")
_("\u201c{name}\u201d already exists on {count} book. Merge this tag into it?")
_("\u201c{name}\u201d already exists on {count} books. Merge this tag into it?")
_("begins with")
_("contains")
_("does not contain")
_("ends with")
_("in the past N days")
_("is not")
_("is")
_("not in the past N days")
_("on or after")
_("on or before")
_("≤")
_("≥")


# ---- "Design a cover" vocabulary (cps/services/cover_generator.py) -------
# The designer's preset, colour-scheme, font and layout labels are backend data
# rendered through `t(o.label)`, so the extractor cannot see them at the call
# site — the same shape that lost the filter-operator list in #1223. They are
# also what the admin page's default-design dropdown renders, so one anchor
# serves both surfaces.
_("Classic")
_("Meadow")
_("Ember")
_("Slate")
_("Plum")
_("Ink on cream")
_("Meadow green")
_("Ember red")
_("Slate grey")
_("Plum violet")
_("Serif")
_("Sans-serif")
_("Blocks — title above, authors on a colour band")
_("Banner — title on a ribbon near the top")
_("Ornamental — title inside a decorative frame")

# ---- "Design a cover" v2 catalogue vocabulary --------------------------------
# cover_generator.CATALOGUE_LABELS: the styles, style descriptions, schemes,
# builtin preset names, text-placeholder labels and per-style colour-role hints
# the v2 catalogue emits. Server data rendered through t(...) — same anchoring
# reason as the v1 block above.
_("Blocks")
_("Banner")
_("Ornamental")
_("The Cross")
_("Half and half")
_("Title at the top, authors on a colour band across the bottom third.")
_("Title on a folded ribbon near the top, authors below on the page.")
_("Title inside a decorated frame over a soft radial wash.")
_("A band down the left edge meeting a rounded title panel.")
_("One colour washing into another from top to bottom.")
_("Earth")
_("Grass")
_("Water")
_("Silver")
_("Midnight")
_("Sepia")
_("Rose")
_("Ocean")
_("Forest")
_("Noir")
_("Calibre blue")
_("Calibre earth")
_("Book title")
_("All authors, separated by commas")
_("First author only")
_("Series name")
_("Number within the series")
_("Publisher")
_("Year of publication")
_("Tags, separated by commas")
_("First language")
_("Rating out of five, as a number")
_("Rating out of five, as stars")
_("Upper two thirds")
_("Bottom third")
_("Title and subtitle")
_("Authors, on the band")
_("Page")
_("The ribbon")
_("Title and subtitle, on the ribbon")
_("Authors, on the page")
_("Centre of the wash")
_("Edge of the wash")
_("Authors, and the ornaments")
_("Left edge and the title panel")
_("Title and subtitle, on the panel")
_("Top and bottom of the wash")
_("Middle of the wash")
_("All three text blocks")
_("Unused by this arrangement")

# Reflow restart-recovery (2026-09): a conversion whose process died mid-run is
# settled as "interrupted" at startup; these are its label and its explanation.
_("Interrupted by a restart")
_("The app restarted before this job recorded completion. Your original PDF is unchanged. Pages already converted may be reused if you retry. Any unresolved charges remain recorded for review; a lost response may still have been charged.")


# ==== BEGIN AUTOGEN (scripts/extract_spa_strings.py --write) ====
# Auto-anchored SPA-only msgids — every t('literal') and static label
# property in frontend/src that
# is not already anchored above. Do NOT edit by hand; run
#   python scripts/extract_spa_strings.py --write
# after adding or removing SPA strings. The CI gate
# (tests/unit/test_spa_strings_anchored.py) fails if this drifts.
_("(no text captured)")
_("(replace cover)")
_("1 selected.")
_("2:3 (publisher cover — no padding for typical covers)")
_("3:4 (generic)")
_("A charge could not be confirmed")
_("A duplicate scan is already running. This list updates when it finishes.")
_("A few random picks from your library")
_("A note about the book, not tied to a passage")
_("A one-time full duplicate scan is needed. Use “Scan for duplicates” above to run it.")
_("A sample")
_("AI review ended before all eligible pages were reviewed. A completed file retains the full source conversion and any approved changes. Compatible responses may be reused; unresolved requests are not retried automatically.")
_("AI review is not available in this build. Source conversion remains available.")
_("AI review stopped at the {amount} cap. The complete source conversion remains in the file; approved changes are included and the remaining pages are unreviewed.")
_("AI review was not requested. Eligibility was not measured; this file uses source conversion and preserves its uncertainty evidence.")
_("API keys")
_("About")
_("Account settings")
_("Account: {name}")
_("Active")
_("Add AI formatting review")
_("Add identifier")
_("Add link")
_("Add note")
_("Add or replace this line in the [OneStoreServices] section:")
_("Add to existing")
_("Add to favorites")
_("Add to library")
_("Admin group")
_("Admin navigation")
_("Admin only")
_("Advanced")
_("Advanced search")
_("Alignment")
_("All")
_("All books")
_("All shelves")
_("Allow remote (magic-link) login")
_("Allowed groups (comma-separated)")
_("An administrator must install it before text can be recovered, or you can keep a facsimile of the page images.")
_("An earlier job left {amount} unconfirmed: a request was sent and its answer never came back, so the provider may still charge it. It is not part of this new cap, and starting again does not settle or erase it.")
_("An installed language code, for example eng, deu, fra, ell.")
_("Annotation pages")
_("Any")
_("Any format")
_("Any language")
_("Any series")
_("Any tags")
_("Apply")
_("Apply metadata")
_("Apply selected")
_("Applying…")
_("Approval counts describe formatting adopted after source and reviewer checks, not independent proof of correctness. An abstention or unchanged page is not an improvement.")
_("Approved operations")
_("Archive")
_("Archived")
_("Arrangement")
_("Ask in Discord")
_("Assign selected to device")
_("Assign to device")
_("Assigned to {name}.")
_("Authentication")
_("Authentication & security")
_("Author A–Z")
_("Author Z–A")
_("Author text")
_("Authorised — signing you in…")
_("Authoritative books")
_("Authorize URL")
_("Authors")
_("Auto-create users")
_("Auto-create users on first login")
_("Back to edit")
_("Back to edit metadata")
_("Back to formatting")
_("Back to library")
_("Background")
_("Band")
_("Base DN")
_("Basic settings")
_("Beta")
_("Between {min} and {max} px. Locked to 2:3, the ratio every cover frame in the app uses.")
_("Black")
_("Bold")
_("Book default")
_("Book density")
_("Book not found.")
_("Book order")
_("Book {id}")
_("Book {number}")
_("Books")
_("Books awaiting authority")
_("Books per page")
_("Books seeding")
_("Books that are not on a Kobo-sync shelf are then removed from the device on its next sync. They stay in your library here.")
_("Build the facsimile EPUB")
_("Built-in")
_("Built-in providers (leave blank to disable):")
_("Bulleted list")
_("CA certificate path")
_("CWA settings")
_("Cached stage results")
_("Can upload books")
_("Cancel")
_("Cancel rename")
_("Cancel title edit")
_("Cancel {task}")
_("Categories")
_("Center")
_("Certificate file path")
_("Certificate path")
_("Change library cover")
_("Check again")
_("Checking…")
_("Choose Login and sign in with this NextGen account or one of its app passwords.")
_("Choose a cover")
_("Choose a cover image to upload")
_("Choose an image…")
_("Choose fields")
_("Choose your theme")
_("Clear default")
_("Clear formatting")
_("Clear selection")
_("Client ID")
_("Client secret")
_("Client secret (leave blank to keep)")
_("Close reader")
_("Code")
_("Colour scheme")
_("Columns")
_("Comfortable")
_("Compact")
_("Configuration")
_("Configure an OpenRouter key to use optional AI review.")
_("Configured")
_("Confirm delete tag {name}")
_("Confirm new password")
_("Confirmed spend")
_("Connect the Kobo to a computer and open .kobo/Kobo/Kobo eReader.conf in a text editor.")
_("Connect this account to an e-reader, then sync once to confirm it reached your library.")
_("Convert")
_("Convert before sending")
_("Convert from")
_("Convert the book")
_("Convert the sample")
_("Convert the whole book")
_("Convert this PDF to EPUB…")
_("Converting")
_("Copied")
_("Copied to clipboard")
_("Copied to clipboard.")
_("Copy link")
_("Copy server address")
_("Copy sync URL")
_("Could not assign.")
_("Could not complete the action.")
_("Could not copy. Select the address and copy it manually.")
_("Could not create shelf.")
_("Could not create the shelf.")
_("Could not delete shelf.")
_("Could not delete tag")
_("Could not delete the Kobo sync URL.")
_("Could not design a cover for this book.")
_("Could not load candidates.")
_("Could not load device annotations.")
_("Could not load duplicates.")
_("Could not load e-readers.")
_("Could not load highlights and notes.")
_("Could not load pairing details.")
_("Could not load reading positions.")
_("Could not load stats.")
_("Could not load tasks.")
_("Could not load the device board.")
_("Could not load this device library.")
_("Could not load this text file.")
_("Could not load users.")
_("Could not open that highlight.")
_("Could not open that search result.")
_("Could not open the synced position.")
_("Could not read this comic archive.")
_("Could not reload metadata")
_("Could not rename shelf.")
_("Could not request deletion from this device.")
_("Could not reset password.")
_("Could not save order.")
_("Could not save reader settings.")
_("Could not save that note.")
_("Could not save the default library filter.")
_("Could not save the preset. Try again.")
_("Could not save the shelf.")
_("Could not save title.")
_("Could not save your reading position.")
_("Could not search this book.")
_("Could not start the duplicate scan.")
_("Could not update pairing details.")
_("Could not update shelf.")
_("Could not update your account setting.")
_("Couldn’t start a magic link. Please try again.")
_("Cover locked")
_("Cover not reachable")
_("Cover save failed.")
_("Cover scope")
_("Cover size")
_("Cover updated from the selected result.")
_("Coverage-limited pages")
_("Create")
_("Create a source-based EPUB with original evidence for uncertain text. Optional AI formatting review has its own estimate and consent.")
_("Create account")
_("Create an account")
_("Create failed.")
_("Create shelf and add book")
_("Create this source conversion without model requests or provider charges.")
_("Create user")
_("Created {name}.")
_("Creating…")
_("Crop to fill — no border, trims the edges")
_("Current")
_("Current cover")
_("Current password")
_("Currently reading")
_("Custom")
_("Custom (based on {name})")
_("Custom border colour")
_("Custom colours")
_("Custom columns")
_("Damaged layer — recovery required")
_("Data hoarder? This will help users organize their accounts!")
_("Database path")
_("Date added")
_("Default (System Sans-Serif)")
_("Default book language")
_("Default interface language")
_("Default library filter cleared.")
_("Default library filter saved.")
_("Default roles for new OAuth users:")
_("Defaults live in Admin → Configuration → Kobo sync.")
_("Delete books")
_("Delete failed.")
_("Delete from device")
_("Delete shelf \"{name}\"? This cannot be undone.")
_("Delete sync URL")
_("Delete tag {name}")
_("Delete the {fmt} file? The book record, metadata, shelves, and reading state stay available.")
_("Delete this Kobo sync URL? The current URL will stop working on every paired Kobo.")
_("Delete this smart shelf? Your books are not affected.")
_("Delete user \"{name}\"? Their shelves and reading data are removed too.")
_("Delete {name}")
_("Delete {name}?")
_("Delete {path} from {name} on its next sync?")
_("Deleted device")
_("Deleted tag {name}")
_("Deleted {name}.")
_("Deletion requested")
_("Dense")
_("Description")
_("Description formatting")
_("Design a cover")
_("Device administration")
_("Device data")
_("Device library")
_("Device name")
_("Device renamed.")
_("Device restored.")
_("Device seen: {name}, last synced {when}. Pairing is working.")
_("Device summary")
_("Device: {name}")
_("Devices")
_("Devices appear here after their first sync.")
_("Disable standard password login")
_("Disabled books")
_("Discover")
_("Discover picks updated.")
_("Discover — Random Picks")
_("Dismiss")
_("Dismiss introduction")
_("Dismiss this group")
_("Display")
_("Documentation")
_("Dog-ears")
_("Done reordering")
_("Download")
_("Download the sample")
_("Drawing the cover…")
_("Drop files here, or click to choose")
_("Duplicate")
_("Duplicate books")
_("Duplicate scan started. It runs in the background — this list updates when it finishes.")
_("Duplicates")
_("E-reader not found")
_("E-reader preview")
_("E-readers")
_("Each account starts with every book it can currently see—not only books it has shelved, read, or downloaded.")
_("Each type (isbn, amazon, google, doi…) may appear once.")
_("Edge blur — soft bokeh border")
_("Edge mirror — extend the artwork (recommended)")
_("Edit")
_("Edit HTML")
_("Edit cover")
_("Edit cover…")
_("Edit custom colours")
_("Edit note")
_("Edit public shelves")
_("Edit smart shelf")
_("Edit title for {title}")
_("Eligibility is not an improvement. Unsupported, limited, declined and unreviewed pages keep the source conversion and its uncertainty evidence.")
_("Eligible pages")
_("Eligible pages in this selection")
_("Email")
_("Email (SMTP) server")
_("Email (optional)")
_("Email claim")
_("Email me a reset")
_("Email server")
_("Email settings saved.")
_("Enable Kobo sync")
_("Encryption")
_("Enter a positive cap within the administrator limit.")
_("Enter at least 2 characters")
_("Every book syncs as it becomes ready. You can exclude individual books below.")
_("Every filled field will replace each book's existing values.")
_("Every page is a picture of the page with OCR text behind it. The words are readable, but the structure has to be rebuilt.")
_("Every selected page gets a source conversion. Optional AI review can suggest supported heading and displayed quotation formatting; it does not rewrite words, repair OCR, or reconstruct tables and notes.")
_("Excluded")
_("Exit full screen")
_("Expires in")
_("Explore the changes, you can always undo later.")
_("Export")
_("Expose only selected shelves over OPDS")
_("Failed")
_("Failed to load shelves.")
_("Failed to load.")
_("Favorite")
_("Favorited")
_("Favorites")
_("Fetch metadata from web")
_("Filed EPUB SHA-256: {hash}")
_("Files")
_("Files are queued for the library's ingest process and appear once imported.")
_("Fill style")
_("Filter by device")
_("Filter {items}")
_("Filter {items}…")
_("Finished")
_("Follow link: {label}")
_("Font")
_("Font family")
_("Font size")
_("Fonts per line, wording, cover size")
_("Forgot password?")
_("Format queued — it will appear once processed.")
_("Formats")
_("Formats — exclude")
_("Formats — include")
_("Formatting is kept where the book page supports it.")
_("Formatting review")
_("From address")
_("Full screen")
_("Full-review reservation ceiling")
_("Generate a new link")
_("Generate a private sync URL for this account. You can delete it at any time.")
_("Generate sync URL")
_("Generating…")
_("Give your smart shelf a name.")
_("Give {name} My Library? It starts as a copy of everything they can see now — nothing changes for them yet.")
_("Go to note")
_("Go to this highlight")
_("Go to your library")
_("Gradient — palette-matched top/bottom blend")
_("Grey")
_("Group by")
_("Group claim")
_("Group members field")
_("Group name")
_("Group object filter")
_("Has pen or drawing notes")
_("Header name")
_("Heading")
_("Height (px)")
_("Help & support")
_("Help menu")
_("Hidden")
_("Hidden built-ins")
_("Hide")
_("Hide Discover section")
_("Hide device details")
_("Hide device library")
_("Hide fields")
_("Hide password")
_("Hide {name}?")
_("Highlight")
_("Highlight saved")
_("Highlights")
_("Highlights and notes")
_("Hot")
_("Hot — Most Downloaded")
_("How much to convert")
_("How should multi-value fields be applied?")
_("How switching between the global library and My Library works")
_("I authorize Luna proposals and Terra reviews through OpenRouter openai/flex, up to {amount} for this job. Unreviewed pages keep the source conversion.")
_("I understand the unconfirmed {amount} from the earlier job may still be charged, and it is not covered by this consent.")
_("Icon")
_("Identifier type")
_("Identifier value")
_("Identifiers")
_("Image from {source}")
_("Import")
_("Import and export")
_("Imported as")
_("In KOReader, open NextGen Progress Sync and choose Set NextGen Server.")
_("In your book")
_("In-browser reading currently supports EPUB. Use download or the classic reader for other formats.")
_("Inactive")
_("Included")
_("Install or update the NextGen Sync plugin.")
_("Instead of forcing all of your books on friends, they can pick which ones they want!")
_("Issuer / base URL")
_("It may have moved, or it might still live in the classic interface.")
_("Italic")
_("Job cap")
_("KOReader")
_("KOReader Progress")
_("Keep the page images as they are. This is a facsimile of the book, not reflowed text.")
_("Key file path")
_("Key path")
_("Kind")
_("Kobo")
_("Kobo Clara HD / 2E / BW / Colour (1072×1448)")
_("Kobo Libra Color / Libra 2 (1264×1680)")
_("Kobo sync URL deleted.")
_("Kobo sync URL ready.")
_("Kobo sync is not enabled on this server.")
_("Kobo sync on")
_("Kobo two-way annotation sync")
_("Kobo two-way sync")
_("Kobo two-way sync: {state}")
_("Language")
_("Language data")
_("Languages")
_("Languages — include")
_("Last modified")
_("Last seen {when}")
_("Last seen: {when}")
_("Last synced")
_("Leave a field empty to use its default.")
_("Left")
_("Legacy gate acceptances")
_("Legacy requests recorded")
_("Lettering")
_("Library cover")
_("Library settings")
_("Line height")
_("Link address")
_("Load more")
_("Loading")
_("Loading device annotations…")
_("Loading device library…")
_("Loading new Discover picks.")
_("Loading pairing details…")
_("Loading reading positions…")
_("Loading…")
_("Local OCR runs before formatting. Uncertain readings remain disclosed with original-source access; some readings cannot be marked at an exact word.")
_("Local time (no OpenRouter credit)")
_("Lock cover")
_("Lock the 2:3 proportions")
_("Login")
_("Login button text")
_("Login method")
_("Login with")
_("Logs")
_("Looks good")
_("Low-res")
_("Luna proposes heading and quotation formatting. Terra reviews each proposal; only approved changes can reach the EPUB.")
_("Magic link")
_("Magic link QR code")
_("Make one from the book's title and author")
_("Make private")
_("Make public")
_("Make this my default library view")
_("Manage admin role from OAuth group")
_("Manage e-readers")
_("Manage presets")
_("Manage presets…")
_("Manage shelves")
_("Manual order")
_("Mark as read")
_("Mark as unread")
_("Match")
_("Max")
_("Max authors shown")
_("Maximum rating")
_("Member user filter")
_("Merge into {name}")
_("Merged into {name}")
_("Metadata URL (OIDC auto-discovery)")
_("Min")
_("Mine")
_("Minimum rating")
_("Mixed lettering — set per line in Advanced.")
_("Model")
_("Models requested")
_("More actions")
_("More actions for {name}")
_("Most of this PDF is not Latin-alphabet text. The selected recognition language will misread it unless a matching language pack is installed.")
_("Move down")
_("Move up")
_("Move {name} down")
_("Move {name} up")
_("My Library is now on for {accounts} accounts.")
_("My Library is on for {accounts} accounts; {errors} accounts failed.")
_("My account")
_("My own cover")
_("My presets")
_("Name")
_("Native text layer (not proofread)")
_("Need to report an issue? Try the new")
_("Never")
_("New")
_("New Feature!")
_("New authors, tags, publishers, and languages will be added after each book's existing values. Filled single-value fields will be replaced.")
_("New password")
_("New shelf name")
_("New shelf name…")
_("New shelf…")
_("New smart shelf")
_("New user")
_("New: My Library")
_("Newest")
_("Newest published")
_("Next")
_("Next page")
_("No books are ready yet — they appear here as they become ready.")
_("No books match this smart shelf right now.")
_("No books match those criteria.")
_("No books were reported in the latest device inventory.")
_("No candidates found yet. Try a different search or refresh.")
_("No contents found.")
_("No duplicate groups found.")
_("No e-readers yet.")
_("No excluded tags")
_("No highlights yet. Select text in the book to make one.")
_("No matches found in this book.")
_("No matching {items} for \"{query}\".")
_("No model requests or provider charges. Keep source text, images, navigation and uncertainty evidence.")
_("No new device check-in yet.")
_("No pages found in this comic.")
_("No presets yet. Save one from the designer.")
_("No reading positions from this device yet.")
_("No recovery — facsimile only")
_("No registered devices.")
_("No shelves yet — create one below.")
_("No shelves yet. Create one above to start collecting books.")
_("No sources need a key.")
_("No tasks running.")
_("No {items} yet.")
_("Not assigned")
_("Not configured")
_("Not in current file")
_("Not installed")
_("Not matched to this library")
_("Not picked")
_("Not seen lately")
_("Not set")
_("Not set up yet")
_("Note")
_("Note removed")
_("Note saved")
_("Note {label}")
_("Notes")
_("Nothing here yet. Highlight or write a note while reading, or import from a Kobo device.")
_("Nothing in this category yet.")
_("Nothing is missing — the global library is still on the server. What you see here is your selection in My Library. Add books from the global library; they appear here and on your e-reader.")
_("Nothing to convert")
_("Nothing to preview yet.")
_("Numbered list")
_("Off by default. While in beta, opting in only records your preference and recovery evidence — it does not change what your Kobo receives yet.")
_("Oldest")
_("Oldest published")
_("On another device where you’re already signed in, scan this code or open the link below to authorise this device.")
_("On this device")
_("One column")
_("One page, downloaded as an EPUB to look at. Nothing is added to your library.")
_("Only the books you pick below sync. Switching here starts from none picked — you choose each book yourself.")
_("Open Account")
_("Open NextGen using an address your e-reader can reach before copying these settings. Localhost only points back to the device itself.")
_("Open admin settings")
_("Open administration")
_("Open classic reader")
_("Open cover editor")
_("Open navigation")
_("Open reader")
_("Open the book")
_("Open the classic interface")
_("Open the link below on your signed-in device.")
_("OpenLDAP server")
_("Opens a prefilled report on GitHub. Nothing is sent until you post it, and you can edit it first.")
_("Opens in classic view")
_("Opt in to Kobo two-way annotation sync")
_("Opting in does not sync a book straight away. Each book is set up and checked first — its real state is shown here.")
_("Optional review uses the two models below, with no automatic alternative route.")
_("Organize your library, your way. Checkout books from the Global Library to bring them into My Library.")
_("Original device attribution restored for {n}.")
_("Original device attribution restored for {ok} of {total}.")
_("PDF reader")
_("Page margins")
_("Page theme")
_("Page {number}")
_("Page {page} of {pages}")
_("Pages")
_("Pages in the sample")
_("Pages in this file")
_("Pages left unreviewed")
_("Pages read with local OCR")
_("Pages sent to a model")
_("Pages with approved changes")
_("Pages with no supported choices")
_("Pair a Kobo or KOReader")
_("Pair an e-reader")
_("Partially seeded books")
_("Password")
_("Password (leave blank to keep)")
_("Paste this server address (the plugin adds /kosync itself):")
_("Paused after a problem")
_("People & devices")
_("Pick a cover from any source we support, paste a URL, upload a file, or use the cover embedded in the book itself.")
_("Picked")
_("Picked up {label}. Drag to reorder, release to drop.")
_("Pictures only — recovery required")
_("Pin sidebar")
_("Pink")
_("Placeholders:")
_("Planned proposer")
_("Planned reviewer")
_("Please give this a try, you can easily undo later.")
_("Port")
_("Position recorded")
_("Position repair queued")
_("Prepare AI estimate")
_("Prepare a local estimate before consenting to review. This reads complete source context and may take time, but sends nothing to a model and reserves no provider credit.")
_("Preparing source context: {page} of {pages}")
_("Preparing your magic link…")
_("Preset")
_("Preset name")
_("Preset saved.")
_("Preview")
_("Preview of the designed cover")
_("Previous")
_("Previous page")
_("Progress")
_("Proposed operations")
_("Proposer abstentions")
_("Provider route")
_("Public")
_("Published after")
_("Published before")
_("Publishers")
_("Quarantined books")
_("Queued")
_("Quote")
_("Random books shown")
_("Rating")
_("Rating (stars)")
_("Ratings")
_("Read pages with no text at all. Existing text layers stay unchanged, including any extraction errors, with source evidence available.")
_("Read status")
_("Read status filter")
_("Reader settings saved.")
_("Reading appearance")
_("Reading positions")
_("Recent")
_("Recipient(s)")
_("Recognition engine")
_("Recognition language")
_("Recover pictures only")
_("Recover the text")
_("Redirect host (full URL)")
_("Reflow PDF to EPUB")
_("Refresh")
_("Registering…")
_("Rejected pages")
_("Reload")
_("Reload metadata for \"{title}\" from the file on disk? Any title, author or series you edited here is replaced by what the file contains. This cannot be undone.")
_("Reload metadata from disk")
_("Reloading…")
_("Remember me")
_("Remove device")
_("Remove from favorites")
_("Remove from library")
_("Remove from shelf")
_("Remove highlight")
_("Remove identifier")
_("Remove link")
_("Remove note")
_("Remove rule")
_("Remove {name}?")
_("Rename")
_("Rename {name}")
_("Reorder")
_("Replace cover with this one?")
_("Replace cover?")
_("Replace existing")
_("Replace metadata for {n} selected book(s)? Those books will lose their existing values in every filled field.")
_("Replace the EPUB this book already has")
_("Report Issue on Discord")
_("Report Issue on GitHub")
_("Report this problem")
_("Requests attempted")
_("Require group membership")
_("Reset password for {name}")
_("Reset password for {name}? Their current password will stop working and a replacement will be emailed.")
_("Reset to defaults")
_("Restore")
_("Restored the previous library mode for {accounts} accounts.")
_("Restoring…")
_("Resume at {percent} from another device")
_("Retry")
_("Reverse-proxy header login")
_("Reviewer abstentions")
_("Revoke the app password \"{label}\"? Any device still using it loses access immediately, and the password cannot be recovered.")
_("Right")
_("Rows per load")
_("Run a sync from the plugin.")
_("Run time")
_("SMTP server")
_("SSL/TLS")
_("STARTTLS")
_("Save")
_("Save as preset")
_("Save email settings")
_("Save for the whole library")
_("Save name")
_("Save note")
_("Save preset")
_("Save security settings")
_("Save settings")
_("Save the file, safely eject the Kobo, then restart it.")
_("Saved. Restart the server for the login changes to take effect.")
_("Scan for duplicates")
_("Scheduled tasks")
_("Scopes")
_("Search inside book")
_("Search sources with different words")
_("Search term")
_("Search this book")
_("Search title, author…")
_("Searching every source…")
_("Searching this book…")
_("Searching…")
_("Security")
_("Security settings saved.")
_("See how each cover looks padded for your device")
_("Seeded books")
_("Select")
_("Select all in group")
_("Select all {n}")
_("Select highlight: {text}")
_("Select multiple")
_("Select note: {text}")
_("Selected books")
_("Send")
_("Send failed.")
_("Send to e-reader")
_("Send-to-eReader email")
_("Sending…")
_("Series index")
_("Series view")
_("Series — include")
_("Serve over HTTPS")
_("Server SSL / HTTPS")
_("Server announcement (shown to all users)")
_("Server host")
_("Server tools")
_("Service account (DN)")
_("Service password")
_("Service password (leave blank to keep)")
_("Set a metadata URL to auto-fill the endpoints below, or enter them manually.")
_("Set up Kobo sync first — then this preference becomes available.")
_("Setting up…")
_("Settings saved.")
_("Shelf name")
_("Shelf not found.")
_("Shelves")
_("Show Discover section")
_("Show Read now and edit buttons")
_("Show Table view")
_("Show all {count} tags")
_("Show all {items}")
_("Show annotations assigned to this device")
_("Show books in language")
_("Show device details")
_("Show e-reader previews on each candidate")
_("Show fewer tags")
_("Show hidden books")
_("Show password")
_("Show the global library again? Your selection is kept exactly as you left it — switch back any time and it is still there. At its next update, your e-reader syncs the global library.")
_("Show {name} the global library again? Their selection is kept but no longer used, and their e-reader syncs the global library at the next update.")
_("Showing the first {count} matches.")
_("Showing {shown} of {total} annotations.")
_("Showing {shown} of {total} books from the latest device inventory.")
_("Shuffle picks")
_("Sidebar pinned.")
_("Sidebar unpinned.")
_("Sign in with a magic link")
_("Sign out")
_("Signing in…")
_("Site title")
_("Size (pt)")
_("Smart shelf not found.")
_("Smart shelves")
_("Solid: average colour of the cover")
_("Solid: custom colour")
_("Solid: most-common colour in the cover")
_("Some sources need a key for better covers")
_("Something went wrong")
_("Something went wrong. Try again.")
_("Sort order")
_("Source conversion")
_("Source conversion is available without a provider key. Optional AI formatting review needs an OpenRouter key.")
_("Source conversion ready; AI review limited")
_("Source details")
_("Source estimate preparation failed. No model request was sent.")
_("Source estimate ready. No credit has been reserved.")
_("Source pages prepared")
_("Source preparation stopped. No model request was sent.")
_("Source recovery")
_("Source text")
_("Start My Library? It begins as everything you can see now, so nothing changes until you remove books yourself. Your e-reader keeps the same books at its next update.")
_("Start the only OAuth provider automatically")
_("Started reading")
_("Starting scan…")
_("Statistics")
_("Status")
_("Stock Kobo")
_("Stock Kobo sync URL")
_("Stop")
_("Stop after spending")
_("Stop preparation")
_("Stopped at the cap")
_("Stopped before it finished")
_("Stretch to fill — no border, slight distortion")
_("Subheading")
_("Subtitle")
_("Support on Ko-fi →")
_("Switch back to My Library? Your library goes back to the books you had chosen — nothing was lost while you saw everything. At its next update, your e-reader returns to your selection.")
_("Switch {name} back to My Library? Their chosen books are restored.")
_("Switching a user to My Library first fills it with everything they can see now, so nothing changes for them until they remove books themselves. Switching back keeps the selection intact but unused.")
_("Sync only my selected shelves")
_("Sync only selected shelves to Kobo")
_("Table view")
_("Tag")
_("Tags")
_("Tags — exclude")
_("Tags — include")
_("Tap Sync on the Kobo. Your NextGen books should appear.")
_("Target aspect ratio")
_("Task")
_("Tasks")
_("Technical details")
_("Text templates")
_("That URL is not a usable image.")
_("The book record, metadata, shelves, and reading state stay available. If this is the last format, you can add a replacement later.")
_("The book was converted")
_("The conversion could not be started.")
_("The global library")
_("The library cover is back for you.")
_("The library is shared and holds every book once — what you keep is My Library. Nothing you had is gone. Every book, new arrivals included, is under Global Library in the menu.")
_("The library is shared and holds every book once — what you keep is My Library. Nothing you had is gone. Your administrator manages what enters it.")
_("The model service stopped answering")
_("The preparation could not be stopped. Try again.")
_("The preset change failed. Try again.")
_("The sample starts at the first body page and keeps the full source context for note and figure associations.")
_("The server draws this cover; nothing is saved until you apply it.")
_("The server-wide option is also off, so nothing can sync yet. An administrator can enable it in the classic server settings.")
_("The whole book")
_("There is no usable text in this PDF, only page images. Text recovery settings determine how those pages are read; review a sample for recognition errors.")
_("There is very little text on each page. This is usually a sparse scan, or two printed pages photographed as one.")
_("This PDF has a native text layer. Extraction and punctuation may still differ from the printed page; original-source evidence remains available.")
_("This PDF has a text layer, but it is not readable words. It has to be treated as if there were no text at all.")
_("This PDF has not been assessed.")
_("This book has no PDF to convert.")
_("This cap may cover only part of the AI review. The complete source conversion will still be produced; pages left unreviewed will be counted explicitly.")
_("This ceiling assumes a proposal and a review request for every eligible page, with no cached responses. It is not an expected bill or money already held. Actual charges and coverage may be lower; your cap limits new requests.")
_("This device will no longer sync.")
_("This e-reader is unavailable or belongs to another account.")
_("This feature is currently disabled at server level.")
_("This format opens in the full-screen reader.")
_("This highlight has no saved position")
_("This keeps the page images as they are — a facsimile of the book, not reflowed text.")
_("This magic link can’t be checked. Generate a new one to try again.")
_("This magic link expired. Generate a new one to try again.")
_("This older job predates the current two-stage review. Its counts are historical and do not establish current review coverage.")
_("This page doesn't exist here.")
_("This page ran into an error and could not be displayed. Your library is fine — reloading usually fixes it.")
_("This shelf is empty. Add books from any book's page.")
_("This stopped when a request’s answer never came back, so its charge could not be confirmed either way. Spent below is confirmed; the unconfirmed amount may still be charged by the provider and stays on record here until it is resolved. Reloading does not settle or erase it, and no new job covers it.")
_("Title A–Z")
_("Title Z–A")
_("Title text")
_("Title, author, or ISBN")
_("Token URL")
_("Too many magic-link checks were made from this network. Generate a new link or try again later.")
_("Top Rated")
_("Trust authentication header")
_("Try My Library")
_("Try again")
_("Two columns")
_("Two-way sync active")
_("Two-way sync preference saved.")
_("Unarchive")
_("Uncertain readings recorded")
_("Unconfirmed, may still be charged")
_("Undo")
_("Undoing…")
_("Unhide")
_("Unknown color")
_("Unknown device")
_("Unknown source")
_("Unlock the 2:3 proportions")
_("Unlock the cover above to apply a new one.")
_("Unlock the cover to change it")
_("Unpin sidebar")
_("Unseeded books")
_("Unsupported pages")
_("Untitled")
_("Untitled link")
_("Update failed.")
_("Upload a book")
_("Upload as cover")
_("Upload books")
_("Uploading is not available for your account on this server.")
_("Use my own cover")
_("Use original device: {name}")
_("Use original devices")
_("Use the library cover")
_("Use these to connect OPDS readers or KOReader sync without your main password.")
_("Use this cover")
_("Use this design")
_("User")
_("User administration")
_("User object filter")
_("User restrictions")
_("Userinfo URL")
_("Username")
_("Username claim")
_("Users")
_("Using the image behind that Google link")
_("Versions")
_("View")
_("View device library")
_("View highlights")
_("View highlights, {count} saved annotations")
_("View settings")
_("Viewer")
_("Waiting for a Kobo or KOReader to sync with this account.")
_("Waiting for you to authorise…")
_("Warning: this highlight can’t be shown in the book")
_("We repaired this book for your Kobo. If you were having trouble highlighting, try after sync — and if it still doesn’t work, remove the book from your Kobo and let it download again.")
_("We repaired this book for your Kobo. If you were having trouble highlighting, try after sync — and if it still doesn’t work, remove the book from your Kobo and let it download again. If you read it some other way, download it again to get the repaired copy.")
_("We repaired {count} books for your Kobo. If you were having trouble highlighting, try after sync — and if it still doesn’t work, remove them from your Kobo and let them download again.")
_("Web reader")
_("What is in this PDF")
_("When locked, fetching metadata will not overwrite this cover.")
_("When reading progress was first synced")
_("Which books sync?")
_("Width (px)")
_("With automatic start on, the login page goes straight to the provider. Add ?local=1 to the login URL to reach the password form, which keeps working as long as standard password login is left enabled.")
_("Write a note")
_("Write a note…")
_("You're probably a long time user of calibre-web. Please let us know your feedback on this, why or why not this works with your flow.")
_("Your Kobo is still set to sync your whole library, so marking this shelf does nothing on its own. Switch your account to shelf-only syncing to make it take effect.")
_("Your Library")
_("Your administrator allows at most {amount} for one conversion.")
_("Your browser cannot play this audio format.")
_("Your cover appears only to you and on books delivered to your e-readers. The library cover stays unchanged for everyone else, and administrators manage it.")
_("Your cover was updated.")
_("Your own cover is private to you and your e-reader deliveries. The library cover stays unchanged for everyone else.")
_("Your personal digital library")
_("Your sample is ready")
_("Your saved e-reader address is shown — change it for this send only.")
_("about {seconds}s for {pages} pages")
_("all rules")
_("any rule")
_("books")
_("books match")
_("copies")
_("e-reader")
_("e.g. Unread sci-fi")
_("eReader email subject")
_("shared")
_("to")
_("type (isbn, amazon, doi…)")
_("unknown")
_("value")
_("you")
_("{count} book")
_("{count} books")
_("{count} file queued for import")
_("{count} file rejected")
_("{count} files queued for import")
_("{count} files rejected")
_("{count} matches")
_("{count} result")
_("{count} results")
_("{count} results for \"{query}\"")
_("{done} of {total}")
_("{field} (comma separated)")
_("{free} free of {total}")
_("{name} hex value")
_("{name} now uses My Library.")
_("{name} removed.")
_("{name} sees the global library again.")
_("{name}, {n} highlights and notes")
_("{n} assigned to {name}.")
_("{n} books in latest inventory")
_("{n} devices · {m} active")
_("{n} failed.")
_("{n} found")
_("{n} highlights and notes")
_("{n} highlights and notes assigned to this device will become Unknown device.")
_("{n} highlights and notes were made on this device. They are not deleted. Their origin history is kept.")
_("{ok} of {total} assigned to {name}.")
_("{ok} of {total} sources answered")
_("{pages} pages are only pictures of pages. They are read off the printed page with local text recognition — a transcription of the source, never a rewrite.")
_("{pages} pages have a text layer that is not readable words. They are read off the printed page with local text recognition — a transcription of the source, never a rewrite.")
_("{pages} pages, added to this book as an EPUB format.")
_("{pages} pages, downloaded as an EPUB to look at. Nothing is added to your library.")
_("{percent}% read")
_("{seeded} of {total} books seeded")
_("← Back")
_("← Back to book")
_("← Back to sign in")
_("← Library")
# ==== END AUTOGEN ====
